// Die wöchentliche Anhebung der Abhängigkeiten (.github/workflows/deps-update.yml).
//
// Entscheidung des Users (24.09.2026, hier übernommen am 26.09.): angehoben
// wird nur, wenn nichts angepasst werden muss — und das wird VOR dem PR
// geprüft. Diese Tests halten fest, dass der Ablauf so gebaut bleibt, und
// prüfen den PR-Text (.github/scripts/deps_pr_text.py) an echten Eingaben.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

final String _wurzel = Directory.current.path;

const String _altLock = '''
# Generated by pub
packages:
  pdfrx:
    dependency: "direct main"
    description:
      name: pdfrx
      sha256: "0000"
      url: "https://pub.dev"
    source: hosted
    version: "2.5.0"
  android_package_installer:
    dependency: "direct main"
    description:
      name: android_package_installer
      sha256: "0000"
      url: "https://pub.dev"
    source: hosted
    version: "0.0.3"
sdks:
  dart: ">=3.6.1 <4.0.0"
''';

String get _neuLock => _altLock
    .replaceFirst('version: "2.5.0"', 'version: "2.6.5"')
    .replaceFirst('version: "0.0.3"', 'version: "0.0.4"');

const String _outdated = '{"packages":[]}';
const String _deps = '{"root":"app","packages":[]}';

Future<ProcessResult> _text(Directory d, List<String> extra) {
  void schreib(String n, String s) => File('${d.path}/$n').writeAsStringSync(s);
  schreib('alt.lock', _altLock);
  schreib('neu.lock', _neuLock);
  schreib('outdated.json', _outdated);
  schreib('deps.json', _deps);
  schreib('pubspec.yaml', 'name: app\n');
  return Process.run('python3', <String>[
    '$_wurzel/.github/scripts/deps_pr_text.py',
    '--alt',
    '${d.path}/alt.lock',
    '--neu',
    '${d.path}/neu.lock',
    '--outdated',
    '${d.path}/outdated.json',
    '--deps',
    '${d.path}/deps.json',
    '--pubspec',
    '${d.path}/pubspec.yaml',
    '--lauf',
    'https://example.org/runs/1',
    ...extra,
  ]);
}

String _datei(String pfad) =>
    File('$_wurzel/$pfad')
        .readAsLinesSync()
        .where((String z) => !z.trimLeft().startsWith('#'))
        .join('\n');

/// Die Jobs des Ablaufs: Name → Text (zwei Leerzeichen eingerückt unter jobs:).
Map<String, String> _jobs() {
  final String ganz = _datei('.github/workflows/deps-update.yml');
  final String teil = ganz.substring(ganz.indexOf('\njobs:\n'));
  final Map<String, String> jobs = <String, String>{};
  String? name;
  final StringBuffer b = StringBuffer();
  for (final String z in teil.split('\n')) {
    final Match? m = RegExp(r'^  ([a-z]+):$').firstMatch(z);
    if (m != null) {
      if (name != null) jobs[name] = b.toString();
      name = m.group(1);
      b.clear();
    }
    b.writeln(z);
  }
  if (name != null) jobs[name] = b.toString();
  return jobs;
}

String _schritt(String job, String name) {
  final List<String> s = <String>[];
  StringBuffer? b;
  for (final String z in job.split('\n')) {
    if (RegExp(r'^      - (name|uses|id):').hasMatch(z)) {
      if (b != null) s.add(b.toString());
      b = StringBuffer();
    }
    b?.writeln(z);
  }
  if (b != null) s.add(b.toString());
  final String t = s.firstWhere(
    (String x) => x.contains(name),
    orElse: () => '',
  );
  expect(t, isNotEmpty, reason: 'Schritt „$name" fehlt');
  return t;
}

void main() {
  late Directory d;
  setUp(() => d = Directory.systemTemp.createTempSync('deps_update_'));
  tearDown(() => d.deleteSync(recursive: true));

  group('PR-Text', () {
    test('Tabelle, Prüfungen, Geräteprobe', () async {
      final ProcessResult r = await _text(d, <String>[]);
      expect(r.exitCode, 0, reason: '${r.stdout}\n${r.stderr}');
      final String t = r.stdout as String;
      expect(t, contains('## Angehoben (2)'));
      expect(
        t,
        contains(
          '| [pdfrx](https://pub.dev/packages/pdfrx/changelog) | 2.5.0 | 2.6.5 | direkt |',
        ),
      );
      expect(
        t,
        contains(
          '- ✅ build-android.yml: Android-Release-APK (arm64), signiert wie der Release',
        ),
      );
      expect(t, contains('PDF ansehen, erzeugen und drucken (pdfrx)'));
      expect(
        t,
        contains(
          'Selbstaktualisierung: ein Update installieren (android_package_installer)',
        ),
      );
      expect(
        t,
        contains('release.yml macht daraus wie aus jedem Push ein Release'),
      );
    });

    test('rote Prüfung: Meldung ohne Häkchen', () async {
      final ProcessResult r = await _text(d, <String>[
        '--gescheitert',
        'build-android.yml',
      ]);
      expect(r.exitCode, 0, reason: '${r.stdout}\n${r.stderr}');
      final String t = r.stdout as String;
      expect(
        t,
        startsWith('## Anhebung zurückgehalten: **build-android.yml** war rot'),
      );
      expect(t, contains('der Prüfzweig ist wieder gelöscht'));
      expect(t, isNot(contains('✅')));
    });
  });

  group('deps-update.yml', () {
    final Map<String, String> j = _jobs();

    test(
      'build-android.yml wird auf dem Prüfzweig gestartet und abgewartet',
      () {
        expect(j.keys, containsAll(<String>['anheben', 'bauten', 'abschluss']));
        expect(j['abschluss'], contains('needs: [anheben, bauten]'));
        final String b = j['bauten']!;
        expect(b, contains('wf=build-android.yml'));
        expect(b, contains('gh workflow run "\$wf" --ref "\$PRUEFZWEIG"'));
        expect(b, contains('gh run watch "\$id" --exit-status'));
        expect(
          b,
          contains('exit \$ROT'),
          reason: 'ein roter Bau muss den Job rot machen',
        );
        for (final String job in <String>['anheben', 'bauten']) {
          expect(j[job], isNot(contains('continue-on-error')), reason: job);
        }
      },
    );

    test('PR nur bei grünem Bau — und nie im Probelauf', () {
      final String a = j['abschluss']!;
      final String pr = _schritt(a, 'Alles grün');
      expect(pr, contains("needs.bauten.result == 'success'"));
      expect(pr, contains("env.PROBE != 'true'"));
      expect(
        pr,
        contains(r'git push -q --force origin "$SHA:refs/heads/$ZWEIG"'),
      );
      expect(pr, contains('gh pr create'));

      final String rot = _schritt(a, 'Etwas war rot');
      expect(rot, isNot(contains('git push')));
      expect(rot, isNot(contains('gh pr')));
      final int probe = rot.indexOf(r'if [ "$PROBE" = "true" ]');
      expect(probe, isNot(-1));
      expect(
        probe,
        lessThan(rot.indexOf('gh issue')),
        reason: 'im Probelauf darf nichts im Issue landen',
      );

      expect(_schritt(a, 'Prüfzweig löschen'), contains('if: always()'));
      final String alles = j.values.join();
      expect(RegExp(r'refs/heads/\$ZWEIG').allMatches(alles).length, 1);
    });
  });

  test('deps-monthly.yml: die Flutter-Fassung wird wirklich eingesetzt', () {
    // Stand bis 26.09.2026: `${ env.FLUTTER_VERSION }` — mit EINER Klammer
    // setzt GitHub nichts ein, flutter-action bekäme den Text wörtlich. Der
    // Monatsbericht war noch nie gelaufen und wäre am 1. rot gewesen.
    final String s = _datei('.github/workflows/deps-monthly.yml');
    expect(s, contains(r'flutter-version: ${{ env.FLUTTER_VERSION }}'));
    expect(RegExp(r'\$\{ env\.').hasMatch(s), isFalse);
  });
}
